In [1]:
import numpy as np
import pandas as pd

import MLutils as ml

In [2]:
X = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

y = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
              [0, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 1, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 0, 0, 0],
              [0, 0, 0, 0, 0, 1, 0, 0],
              [0, 0, 0, 0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 1]])

# Question 1

In [3]:
# Implement the Neural Network
nn = ml.NeuralNetwork()
nn.train(X, y)
nn_pred = nn.predict()

Predicted data based on trained weights: 
Input (scaled): 
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
Hidden Layer: 
[[-4.51717921  3.97674842  2.76370784]
 [ 4.37042637 -4.68266456  1.4699174 ]
 [-0.86356733 -1.43901131 -1.11995057]
 [-0.18882909  4.80366357 -2.86219488]
 [-1.05866795 -1.64740541  4.90317215]
 [-1.52258544 -0.84531414 -0.95242475]
 [ 4.75092404  0.30864824 -3.96569433]
 [-1.0866874  -1.18964752 -1.3066696 ]]
Output: 
[[9.10160024e-01 2.26332214e-07 1.48049002e-02 1.49732067e-02
  3.05432949e-02 1.22501752e-01 1.02345515e-07 3.13275627e-02]
 [9.97955171e-07 9.11486870e-01 1.10988333e-01 2.59381264e-07
  3.55344721e-02 1.68428175e-02 1.32213859e-02 5.45029518e-02]
 [2.53227732e-02 1.30252258e-01 2.45543459e-01 3.14714009e-02
  6.09195411e-02 2.04281578e-01 9.44233123e-02 2.36574958e-01]
 [2.46019887e-02 7.02006940e-06 4.79178789e-02 9.21214225e-01
  3.24917648e-

# Question 2

In [4]:
# Create an Autoencoder using Tensorflow
autoencoder = ml.AutoencoderTF()
autoencoder.train(X, y)
ae_pred = autoencoder.test(y)

2023-10-12 13:16:28.119135: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1/1 [==============================] - 0s 23ms/step
Input Data: [[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
Predicted data based on trained weights: [[9.2626441e-01 1.7356340e-02 1.7617779e-02 2.4874823e-02 2.7059108e-02
  1.4356785e-03 3.0300116e-02 8.7491184e-04]
 [4.9239728e-03 9.8689270e-01 2.1292002e-12 4.9195383e-25 8.2915910e-03
  5.2049266e-21 5.4161162e-03 2.3729567e-13]
 [4.0700873e-03 6.7681272e-10 9.8667860e-01 8.1591737e-03 8.7431734e-03
  8.0648604e-12 1.4066127e-19 4.0584240e-23]
 [1.5706982e-02 2.1165885e-11 1.2368001e-02 9.8257548e-01 2.1229911e-09
  1.4497644e-02 5.5384855e-12 6.3432415e-10]
 [2.1151599e-02 8.5675893e-03 8.5377730e-03 4.9810248e-13 9.8488832e-01
  5.2839160e-18 1.2340741e-12 2.9081499e-21]
 [3.1598647e-05 3.3188749e-17 1.0091705e-11 1.0618368e-02 5.3957106e-22
  9.8367769e-01 1.4310019e-09 1.2561655e-02]
 [1.3148788e-02 1.1765053e-02 1.1711662e

In [5]:
# Compare the results of the Autoencoder and the Neural Network using mean squared error (MSE)

# use argmax to select the only maximum as 1 and convert the results to one-hot labels
nn_pred_idx = np.argmax(nn_pred, axis=1)
nn_pred_idx = np.eye(8)[nn_pred_idx]

ae_pred_idx = np.argmax(ae_pred, axis=1)
ae_pred_idx = np.eye(8)[ae_pred_idx]

print("Neural Network Output: \n" + str(nn_pred_idx))
print("Autoencoder Output: \n" + str(ae_pred_idx))

accuracy = np.sum(nn_pred_idx == ae_pred_idx) / len(ae_pred_idx) / 8
print("Accuracy: " + str(accuracy))

Neural Network Output: 
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
Autoencoder Output: 
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
Accuracy: 1.0


# Question 3

In [6]:
# Load the wine dataset
train_wine = pd.read_csv('train_wine.csv')
test_wine = pd.read_csv('test_wine.csv')

display(train_wine)
display(test_wine)

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  \
0    2  11.65  1.67  2.62  26.0   88  1.92  1.61  0.40  1.34  2.60  1.36   
1    2  11.41  0.74  2.50  21.0   88  2.48  2.01  0.42  1.44  3.08  1.10   
2    3  13.78  2.76  2.30  22.0   90  1.35  0.68  0.41  1.03  9.58  0.70   
3    1  13.30  1.72  2.14  17.0   94  2.40  2.19  0.27  1.35  3.95  1.02   
4    1  13.29  1.97  2.68  16.8  102  3.00  3.23  0.31  1.66  6.00  1.07   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   
145  2  12.51  1.73  1.98  20.5   85  2.20  1.92  0.32  1.48  2.94  1.04   
146  2  13.34  0.94  2.36  17.0  110  2.53  1.30  0.55  0.42  3.17  1.02   
147  2  12.77  3.43  1.98  16.0   80  1.63  1.25  0.43  0.83  3.40  0.70   
148  1  14.10  2.02  2.40  18.8  103  2.75  2.92  0.32  2.38  6.20  1.07   
149  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06  7.70  0.64   

     3.92  1065  
0    3.21   562  
1    2.31   434  
2    1.68   615  
3    2.77  1285  
4    2.84  1270  
..    ...   ...  
145  3.57   672  
146  1.93   750  
147  2.12   372  
148  2.75  1060  
149  1.74   740  

[150 rows x 14 columns]

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0   1  13.56  1.73  2.46  20.5  116  2.96  2.78  0.20  2.45   6.25  0.98   
1   3  12.79  2.67  2.48  22.0  112  1.48  1.36  0.24  1.26  10.80  0.48   
2   2  12.17  1.45  2.53  19.0  104  1.89  1.75  0.45  1.03   2.95  1.45   
3   1  14.22  1.70  2.30  16.3  118  3.20  3.00  0.26  2.03   6.38  0.94   
4   2  11.87  4.31  2.39  21.0   82  2.86  3.03  0.21  2.91   2.80  0.75   
5   2  12.42  4.43  2.73  26.5  102  2.20  2.13  0.43  1.71   2.08  0.92   
6   1  14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98   5.20  1.08   
7   3  12.36  3.83  2.38  21.0   88  2.30  0.92  0.50  1.04   7.65  0.56   
8   2  12.72  1.75  2.28  22.5   84  1.38  1.76  0.48  1.63   3.30  0.88   
9   2  12.00  1.51  2.42  22.0   86  1.45  1.25  0.50  1.63   3.60  1.05   
10  3  13.45  3.70  2.60  23.0  111  1.70  0.92  0.43  1.46  10.68  0.85   
11  3  13.88  5.04  2.23  20.0   80  0.98  0.34  0.40  0.68   4.90  0.58   
12  1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98   5.25  1.02   
13  2  12.29  3.17  2.21  18.0   88  2.85  2.99  0.45  2.81   2.30  1.42   
14  3  13.58  2.58  2.69  24.5  105  1.55  0.84  0.39  1.54   8.66  0.74   
15  2  12.72  1.81  2.20  18.8   86  2.20  2.53  0.26  1.77   3.90  1.16   
16  1  13.51  1.80  2.65  19.0  110  2.35  2.53  0.29  1.54   4.20  1.10   
17  1  13.64  3.10  2.56  15.2  116  2.70  3.03  0.17  1.66   5.10  0.96   
18  2  13.67  1.25  1.92  18.0   94  2.10  1.79  0.32  0.73   3.80  1.23   
19  1  13.82  1.75  2.42  14.0  111  3.88  3.74  0.32  1.87   7.05  1.01   
20  2  12.37  1.17  1.92  19.6   78  2.11  2.00  0.27  1.04   4.68  1.12   
21  1  13.07  1.50  2.10  15.5   98  2.40  2.64  0.28  1.37   3.70  1.18   
22  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
23  2  12.42  2.55  2.27  22.0   90  1.68  1.84  0.66  1.42   2.70  0.86   
24  2  12.64  1.36  2.02  16.8  100  2.02  1.41  0.53  0.62   5.75  0.98   
25  2  11.76  2.68  2.92  20.0  103  1.75  2.03  0.60  1.05   3.80  1.23   
26  2  11.79  2.13  2.78  28.5   92  2.13  2.24  0.58  1.76   3.00  0.97   

    3.92  1065  
0   3.03  1120  
1   1.47   480  
2   2.23   355  
3   3.31   970  
4   3.64   380  
5   3.12   365  
6   2.85  1045  
7   1.58   520  
8   2.42   488  
9   2.65   450  
10  1.56   695  
11  1.33   415  
12  3.58  1290  
13  2.83   406  
14  1.80   750  
15  3.14   714  
16  2.87  1095  
17  3.36   845  
18  2.46   630  
19  3.26  1190  
20  3.48   510  
21  2.69  1020  
22  2.85  1450  
23  3.30   315  
24  1.59   450  
25  2.50   607  
26  2.44   466

In [7]:
# Normalize the data
train_wine.iloc[:, 1:], train_avg, train_stdev = ml.normalize(train_wine.iloc[:, 1:])
test_wine.iloc[:, 1:] = (test_wine.iloc[:, 1:] - train_avg) / train_stdev

display(train_wine)
display(test_wine)

1     14.23      1.71      2.43      15.6       127       2.8      3.06  \
0    2 -1.670125 -0.586254  0.923595  1.981185 -0.810781 -0.612897 -0.384151   
1    2 -1.970387 -1.408850  0.494238  0.454064 -0.810781  0.289686  0.007108   
2    3  0.994702  0.377863 -0.221358  0.759488 -0.673205 -1.531598 -1.293826   
3    1  0.394178 -0.542029 -0.793834 -0.767633 -0.398053  0.160746  0.183174   
4    1  0.381667 -0.320901  1.138274 -0.828718  0.152251  1.127799  1.200446   
..  ..       ...       ...       ...       ...       ...       ...       ...   
145  2 -0.594185 -0.533184 -1.366310  0.301352 -1.017145 -0.161605 -0.080925   
146  2  0.444221 -1.231948 -0.006679 -0.767633  0.702554  0.370274 -0.687376   
147  2 -0.268901  0.970486 -1.366310 -1.073057 -1.361085 -1.080306 -0.736283   
148  1  1.395051 -0.276675  0.136440 -0.217869  0.221039  0.724860  0.897221   
149  3  0.907125  2.934102  0.315339  0.301352 -0.329265 -0.999718 -1.362297   

          .28      2.29      5.64      1.04      3.92      1065  
0    0.324537 -0.430475 -1.052111  1.781424  0.864654 -0.608422  
1    0.486267 -0.255722 -0.845966  0.645535 -0.405789 -1.017432  
2    0.405402 -0.972209  1.945577 -1.101987 -1.295098 -0.439067  
3   -0.726705 -0.413000 -0.472329  0.296030  0.243549  1.701840  
4   -0.403246  0.128735  0.408081  0.514470  0.342361  1.653909  
..        ...       ...       ...       ...       ...       ...  
145 -0.322381 -0.185821 -0.906092  0.383406  1.372831 -0.256930  
146  1.537509 -2.038203 -0.807314  0.296030 -0.942198 -0.007690  
147  0.567132 -1.321715 -0.708537 -1.101987 -0.673993 -1.215545  
148 -0.322381  1.386956  0.493974  0.514470  0.215316  0.982879  
149  1.294914 -0.919783  1.138177 -1.364116 -1.210402 -0.039644  

[150 rows x 14 columns]

1     14.23      1.71      2.43      15.6       127       2.8      3.06  \
0   1  0.719462 -0.533184  0.351119  0.301352  1.115282  1.063329  0.760280   
1   3 -0.243880  0.298257  0.422678  0.759488  0.840130 -1.322069 -0.628687   
2   2 -1.019557 -0.780847  0.601577 -0.156784  0.289827 -0.661250 -0.247210   
3   1  1.545182 -0.559719 -0.221358 -0.981430  1.252858  1.450150  0.975472   
4   2 -1.394885  1.748856  0.100660  0.454064 -1.223509  0.902153  1.004817   
5   2 -0.706784  1.854998  1.317173  2.133897  0.152251 -0.161605  0.124485   
6   1  2.308349 -0.612790 -0.686495 -1.683906 -0.191689  0.805448  0.955909   
7   3 -0.781849  1.324291  0.064881  0.454064 -0.810781 -0.000430 -1.059071   
8   2 -0.331456 -0.515493 -0.292917  0.912200 -1.085933 -1.483245 -0.237429   
9   2 -1.232243 -0.727776  0.208000  0.759488 -0.948357 -1.370422 -0.736283   
10  3  0.581841  1.209304  0.852036  1.064913  0.771342 -0.967483 -1.059071   
11  3  1.119811  2.394550 -0.471816  0.148640 -1.361085 -2.127947 -1.626396   
12  1  1.757868 -0.409352  0.315339 -1.500651 -0.260477  0.321921  0.505962   
13  2 -0.869426  0.740513 -0.543375 -0.462209 -0.810781  0.886036  0.965691   
14  3  0.744483  0.218651  1.174054  1.523049  0.358615 -1.209247 -1.137323   
15  2 -0.331456 -0.462423 -0.579155 -0.217869 -0.948357 -0.161605  0.515744   
16  1  0.656907 -0.471268  1.030935 -0.156784  0.702554  0.080158  0.515744   
17  1  0.819549  0.678597  0.708917 -1.317397  1.115282  0.644272  1.004817   
18  2  0.857082 -0.957749 -1.580989 -0.462209 -0.398053 -0.322781 -0.208084   
19  1  1.044746 -0.515493  0.208000 -1.683906  0.771342  2.546144  1.699300   
20  2 -0.769338 -1.028510 -1.580989  0.026470 -1.498661 -0.306663 -0.002674   
21  1  0.106426 -0.736621 -0.936953 -1.225769 -0.122901  0.160746  0.623340   
22  1  1.520161 -0.506648  0.315339 -1.317397  0.840130  1.562973  1.356949   
23  2 -0.706784  0.192116 -0.328697  0.759488 -0.673205 -0.999718 -0.159177   
24  2 -0.431543 -0.860453 -1.223191 -0.828718  0.014675 -0.451721 -0.579780   
25  2 -1.532505  0.307102  1.996988  0.148640  0.221039 -0.886895  0.026671   
26  2 -1.494972 -0.179379  1.496072  2.744746 -0.535629 -0.274428  0.232081   

         .28      2.29      5.64      1.04      3.92      1065  
0  -1.292758  1.509284  0.515448  0.121278  0.610565  1.174602  
1  -0.969299 -0.570277  2.469528 -2.063124 -1.591535 -0.870444  
2   0.728861 -0.972209 -0.901797  2.174616 -0.518717 -1.269867  
3  -0.807569  0.775321  0.571279 -0.053474  1.005814  0.695294  
4  -1.211893  2.313147 -0.966218 -0.883547  1.471643 -1.189982  
5   0.567132  0.216111 -1.275435 -0.140850  0.737609 -1.237913  
6  -0.564975  0.687944  0.064506  0.558158  0.356477  0.934948  
7   1.133185 -0.954734  1.116703 -1.713620 -1.436259 -0.742629  
8   0.971455  0.076309 -0.751483 -0.315602 -0.250512 -0.844881  
9   1.133185  0.076309 -0.622643  0.427094  0.074156 -0.966305  
10  0.567132 -0.220771  2.417992 -0.446667 -1.464491 -0.183436  
11  0.324537 -1.583845 -0.064334 -1.626244 -1.789159 -1.078144  
12 -0.484110  0.687944  0.085980  0.296030  1.386947  1.717817  
13  0.728861  2.138394 -1.180952  2.043552  0.328245 -1.106902  
14  0.243672 -0.080969  1.550466 -0.927235 -1.125706 -0.007690  
15 -0.807569  0.320963 -0.493803  0.907663  0.765842 -0.122724  
16 -0.564975 -0.080969 -0.364962  0.645535  0.384709  1.094717  
17 -1.535352  0.128735  0.021559  0.033902  1.076394  0.295871  
18 -0.322381 -1.496468 -0.536749  1.213479 -0.194048 -0.391136  
19 -0.322381  0.495716  0.859022  0.252342  0.935234  1.398279  
20 -0.726705 -0.954734 -0.158817  0.732911  1.245786 -0.774582  
21 -0.645840 -0.378049 -0.579696  0.995039  0.130620  0.855063  
22 -0.160651  0.670469  0.730182  0.427094  0.356477  2.229079  
23  2.427021 -0.290673 -1.009164 -0.402979  0.991698 -1.397682  
24  1.375779 -1.688697  0.300714  0.121278 -1.422143 -0.966305  
25  1.941833 -0.937259 -0.536749  1.213479 -0.137584 -0.464630  
26  1.780103  0.303488 -0.880324  0.

In [8]:
# Train the multi-class neural network on the wine dataset
train_x = train_wine.iloc[:, 1:]
train_y = train_wine.iloc[:, 0]

# convert the labels to one-hot labels
# subtract 1 from the labels to make them 0, 1, 2 instead of 1, 2, 3
train_y = train_y - 1
train_y = np.eye(3)[train_y]

test_x = test_wine.iloc[:, 1:]
test_y = test_wine.iloc[:, 0]

mnn = ml.MultiNeuralNetwork()
mnn.train(train_x, train_y)
mnn_pred = mnn.predict(test_x)
print(mnn_pred)

Predicted data based on trained weights: [[9.91107233e-01 9.47904603e-05 6.17151520e-03]
 [5.54448598e-04 9.49507916e-03 9.88033254e-01]
 [7.09619190e-05 9.99908066e-01 1.26473628e-03]
 [9.89553520e-01 6.25271048e-05 2.78322935e-03]
 [1.65008300e-03 9.84647154e-01 3.89037949e-03]
 [2.00009701e-04 9.90933267e-01 9.34436960e-03]
 [9.81396454e-01 2.10702185e-04 7.59193433e-04]
 [2.95391605e-03 1.70934774e-03 9.96905899e-01]
 [2.41153941e-04 9.98722943e-01 1.03781589e-02]
 [2.61218067e-04 9.99090752e-01 1.10109911e-02]
 [7.68849960e-03 1.00254146e-03 9.91202043e-01]
 [3.67425146e-03 8.77039368e-04 9.97494943e-01]
 [9.98712972e-01 4.10652018e-06 4.13902717e-02]
 [1.84628314e-02 9.98291048e-01 5.94510302e-04]
 [3.19943240e-03 1.58023270e-03 9.91190986e-01]
 [3.71810598e-01 9.62424377e-01 5.30919604e-06]
 [9.92098619e-01 5.75151264e-04 2.34226575e-03]
 [9.92417252e-01 2.89124485e-05 9.66372604e-03]
 [2.54747170e-03 6.82002210e-01 5.50433343e-04]
 [9.96730046e-01 2.45352022e-04 2.22444824e-03]

In [9]:
# Compare the results of the multi-class neural network and the test labels
mnm_pred_idx = np.argmax(mnn_pred, axis=1)
mnm_pred_idx = np.eye(3)[mnm_pred_idx]

test_y_idx = test_y - 1
test_y_idx = np.eye(3)[test_y_idx]

print("Multi-class Neural Network Output: \n" + str(mnm_pred_idx))
print("Test Labels: \n" + str(test_y_idx))

accuracy = np.sum(mnm_pred_idx == test_y_idx) / len(test_y_idx) / 3
print("Accuracy: " + str(accuracy))

Multi-class Neural Network Output: 
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Test Labels: 
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Accuracy: 1.0


# Question 4

In [10]:
# Train the multi-class neural network using Tensorflow on the wine dataset
mnn_tf = ml.AutoencoderTF(8, 3)
mnn_tf.train(train_x, train_y)
mnn_tf_pred = mnn_tf.test(test_x)
print(mnn_tf_pred)

1/1 [==============================] - 0s 15ms/step
Input Data:        14.23      1.71      2.43      15.6       127       2.8      3.06  \
0   0.719462 -0.533184  0.351119  0.301352  1.115282  1.063329  0.760280   
1  -0.243880  0.298257  0.422678  0.759488  0.840130 -1.322069 -0.628687   
2  -1.019557 -0.780847  0.601577 -0.156784  0.289827 -0.661250 -0.247210   
3   1.545182 -0.559719 -0.221358 -0.981430  1.252858  1.450150  0.975472   
4  -1.394885  1.748856  0.100660  0.454064 -1.223509  0.902153  1.004817   
5  -0.706784  1.854998  1.317173  2.133897  0.152251 -0.161605  0.124485   
6   2.308349 -0.612790 -0.686495 -1.683906 -0.191689  0.805448  0.955909   
7  -0.781849  1.324291  0.064881  0.454064 -0.810781 -0.000430 -1.059071   
8  -0.331456 -0.515493 -0.292917  0.912200 -1.085933 -1.483245 -0.237429   
9  -1.232243 -0.727776  0.208000  0.759488 -0.948357 -1.370422 -0.736283   
10  0.581841  1.209304  0.852036  1.064913  0.771342 -0.967483 -1.059071   
11  1.119811  2.394550 -

In [11]:
# Compare the results of the multi-class neural network, test labels, and the multi-class neural network using Tensorflow
mnn_tf_pred_idx = np.argmax(mnn_tf_pred, axis=1)
mnn_tf_pred_idx = np.eye(3)[mnn_tf_pred_idx]

print("Multi-class Neural Network Output: \n" + str(mnm_pred_idx))
print("Multi-class Neural Network using Tensorflow Output: \n" + str(mnn_tf_pred_idx))
print("Test Labels: \n" + str(test_y_idx))

accuracy = np.sum(mnn_tf_pred_idx == test_y_idx) / len(test_y_idx) / 3
print("Accuracy: " + str(accuracy))

Multi-class Neural Network Output: 
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Multi-class Neural Network using Tensorflow Output: 
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Test Labels: 
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1.